/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
export type { ERC4626 } from "./ERC4626";
export type { ERC4626OpenZepplin } from "./ERC4626OpenZepplin";
export type { IERC4626 } from "./IERC4626";
